version: "3.7"

services:
  my_app:
    environment:
      PGHOST: postgresql
      PGDATABASE: db
      PGUSER: user
      PGPASSWORD: password123
    depends_on:
      - postgresql

  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123

