version: "3.7"

services:
  my_app:
    environment:
      PGHOST: db
      PGDATABASE: my_app
      PGUSER: my_app
      PGPASSWORD: my_app123
    depends_on:
      - db

  db:
    image: postgres:9.6    
    environment:
      POSTGRES_USER: my_app
      POSTGRES_PASSWORD: my_app123
