version: "3.7"

services:
  my_app:
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password123
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password123
